apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: msync-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msync-api
  template:
    metadata:
      labels:
        app: msync-api
    spec:
      containers:
        - name: msync-api
          image: msync-api
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /admin/login/?next=/admin/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /admin/login/?next=/admin/
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 120
          env:
            - name: CELERY_BROKER_URL
              value: redis://192.168.1.12:6379
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: msync-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
